---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: debian-9
    image: debian:9
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    destroy: ../default/destroy.yml
    prepare: ../default/prepare.yml
    converge: playbook.yml
  lint:
    name: ansible-lint
  inventory:
    links:
      group_vars: ../default/inventory/group_vars/
scenario:
  name: cnc
verifier:
  name: testinfra
  lint:
    name: flake8
